GET http://localhost:5021/games

###
GET http://localhost:5021/games/4

###
POST http://localhost:5021/games
Content-Type: application/json

{
    "name": "Mincecraft",
    "genre": "Kids and Family",
    "price": 19.99,
    "releaseDate": "2011-11-18"
}